import { Route } from "../utils/interfaces";

let bass = require('../audio/bass16b.wav');

export const TrainAudioMap: Record < Route, string > = {
  [Route.ONE]: bass,
  [Route.TWO]: bass,
  [Route.THREE]: bass,
  [Route.FOUR]: bass,
  [Route.FIVE]: bass,
  [Route.SIX]: bass,
  [Route.SIXX]: bass,
  [Route.SEVEN]: bass,
  [Route.SEVENX]: bass,
  [Route.A]: bass,
  [Route.B]: bass,
  [Route.C]: bass,
  [Route.D]: bass,
  [Route.E]: bass,
  [Route.F]: bass,
  [Route.FS]: bass,
  [Route.FX]: bass,
  [Route.G]: bass,
  [Route.GS]: bass,
  [Route.H]: bass,
  [Route.J]: bass,
  [Route.L]: bass,
  [Route.M]: bass,
  [Route.N]: bass,
  [Route.Q]: bass,
  [Route.R]: bass,
  [Route.S]: bass,
  [Route.SF]: bass,
  [Route.SI]: bass,
  [Route.SIR]: bass,
  [Route.SR]: bass,
  [Route.SS]: bass,
  [Route.W]: bass,
  [Route.Z]: bass,
};
